pipeline {
    agent any

    stages {
        stage('Authenticate with ECR') {
            steps {
                script {
                    def region = 'us-east-1'
                    withCredentials([usernamePassword(credentialsId: 'aws-credentials', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                        sh "aws ecr-public get-login-password --region ${region} | docker login --username AWS --password-stdin public.ecr.aws/${region}"
                    }
                }
            }
        }
        stage('Build Docker Image,Tag and push') {
            steps {
                script {
                    sh """
                        docker build -t simple-webserver:v1 .
                        docker tag simple-webserver:v1 public.ecr.aws/${region}/simple-webserver:v1
                        docker push public.ecr.aws/${region}/simple-webserver:v1
                      """
                }
            }
        }
    }
}
